# Generated by Django 5.0.3 on 2024-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elevation',
        ),
    ]
