# Generated by Django 5.0.3 on 2024-04-03 12:16

import django.db.models.deletion
import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='box',
            field=models.ForeignKey(default=support.models.Box.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='support.box'),
        ),
    ]
