# Generated by Django 5.0.3 on 2024-04-03 20:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_pickup_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-95.9, 41.2), srid=4326),
        ),
    ]
