# Generated by Django 5.0.3 on 2024-04-04 11:23

import datetime
import scenarios.models.scenario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_pickup_location_alter_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='saved_simulated_attribute_hash',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='pickup',
            name='saved_simulated_attribute_hash',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='altitude_ft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='offset',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unnamed Order', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='offset',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='altitude_ft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='offset',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='exercise_start_datetime',
            field=models.DateTimeField(default=scenarios.models.scenario.default_midnight_today),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(default='Unnamed Scenario', max_length=100),
        ),
    ]
