# Generated by Django 5.0.3 on 2024-04-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_delivery_saved_simulated_attribute_hash_and_more'),
        ('support', '0002_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.worldborder'),
        ),
    ]
