# Generated by Django 5.0.3 on 2024-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0007_delivery_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='calculated_altitude_ft',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pickup',
            name='calculated_altitude_ft',
            field=models.FloatField(default=0),
        ),
    ]
